### ISSUE TITLE
Video processing process document

### ISSUE THREAD

**Issue by hsb1007** [kuky-com/backend#3]
1. Start recording button 

2. Live view of user recording himself 

![Image](https://github.com/user-attachments/assets/333ad719-f960-4f75-a2e0-32e064fcbf6b)

- While video is being recorded, transcribe (This part at later stage)

3. Video review page where user can replay the video and confirm
![Image](https://github.com/user-attachments/assets/36dffaeb-957a-4ac5-9ef4-b3285a193280)

4. Once user confirms, compress / save compressed video in s3 bucket/ and send to the API
5.

**Comment by hsb1007** [comment]
@tungmt  Let me know what you thnikk

**Comment by tungmt** [comment]
Yes, it is easiest way to solve this problem. Use s3 storage for now. @hsb1007
