### ISSUE TITLE
DB credentail to be shared

### ISSUE THREAD

**Issue by hsb1007** [kuky-com/backend#4]

**Comment by tungmt** [comment]
{
  "development": {
    "username": "admin",
    "password": "5uDop94oomy&v(N",
    "database": "kuky",
    "host": "127.0.0.1",
    "dialect": "postgres",
    "port": 5428
  },
  "test": {
    "username": "admin",
    "password": "5uDop94oomy&v(N",
    "database": "kuky",
    "host": "127.0.0.1",
    "dialect": "postgres",
    "port": 5428
  },
  "production": {
    "username": "admin",
    "password": "5uDop94oomy&v(N",
    "database": "kuky",
    "host": "52.65.80.111",
    "dialect": "postgres",
    "port": 5428
  },
  "staging": {
    "username": "admin",
    "password": "5uDop94oomy&v(N",
    "database": "kuky",
    "host": "54.253.118.218",
    "dialect": "postgres",
    "port": 5428
  }
}
